### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by marchersimon** [LukWebsForge/TldrProgress#13]
It would be awesome if there was a dark mode. Either as default or optional. My proposal (heavily inspired by the GitHub dark theme):

* Background: `#0d1117`
* Font: `#f0f6fc`
* Table header: `#0d1117`
* "Platform" cells: `#161b20`
* Table border: `#21262d`
* Red cells: `#592527`
* Green cells: `#1c512c`
* Yellow cells: `#796713`

This is what it looks like (except for the table border, I couldn't get that to work):
<img src="https://user-images.githubusercontent.com/50295997/120855855-4d19ff80-c57f-11eb-964a-90ca1672f209.png" style="border:10px solid white;">
I'm not perfectly happy on the red, green and yellow cells, but I think it's good enough.

**Comment by LukBukkit** [comment]
That's a good idea and your color selections looks nice :D

Some thoughts:
* Geist UI supports a [dark mode](https://react.geist-ui.dev/en-us/guide/themes), but as our tables are custom built we can use your colors for those
* There should be a new action button to change the theme
  * Should the button be positioned next to the help action (just visible at the top) or near the other buttons (also visible while scrolling)?
  * I would prefer to place it on the top left, because I guess that most people change the theme just once at the start of their visit and not while scrolling through the pages
* We should persist the color selection (just like the highlighted columns)
    * For how long? At which point should we use the system default (see below) again?
* Should we initially apply the system theme using a [use-system-theme](https://github.com/xcv58/use-system-theme) hook?

**Comment by bl-ue** [comment]
My thoughts:

>There should be a new action button to change the theme
>I would prefer to place it on the top left, because I guess that most people change the theme just once at the start of their visit and not while scrolling through the pages

Option 2 sounds the best to me.

>We should persist the color selection (just like the highlighted columns)
>For how long? At which point should we use the system default (see below) again?

Forever until the user changes it, I'd say.

>Should we initially apply the system theme using a use-system-theme hook?

Yes, definitely.

**Comment by LukBukkit** [comment]
> Option 2 sounds the best to me.

So you think we should place it at the top right near the other buttons, correct?
