### ISSUE TITLE
Add a filter for outdated translations

### ISSUE THREAD

**Issue by navarroaxel** [LukWebsForge/TldrProgress#9]
As a user I want to filter the outdated pages for a specific language to work on them and update :muscle:

**Comment by LukBukkit** [comment]
Yeah that's a good idea. It shouldn't be too hard to implement, thanks to the adaptation of React. But I'm not yet sure when I've got time to implement this feature. Everyone is welcome to help.
Also inspirations for the UI and UX of this feature could be useful.

**Comment by LukBukkit** [comment]
I've drawn a bit and created a new design for the page. An icon bar at the top of the translation table is used for different special functionalities like the quick jump feature, this filter feature or a search feature. Because the design was created with a frame for the table in mind, I'm going to use react-window and thus fix #7.

Here's a rough idea of the design
![grafik](https://user-images.githubusercontent.com/8070210/116116437-73649980-a6bb-11eb-9892-570a766ede52.png)

**Comment by LukBukkit** [comment]
I've implemented a filter feature while redesigning the front end. Check the pull request #11 for more details.
